name: Depoly html page to fast-fire server
on:
  push:
    branches:
      - gh-page
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.USER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.USER_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: "/home/${{ secrets.USER_NAME }}/pages/$GITHUB_REPOSITORY"